os:
  - linux

language: php

php:
  - 7.4
node_js:
  - "12"

services:
  - mysql

before_script:
  - chmod 777 -R storage
  - cp .env.travis .env
  - mysql -e 'create database keex'
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php artisan key:generate
  - php artisan storage:link
  #- php artisan migrate:fresh --seed
  - npm install
  - npm run dev

cache:
  directories:
    - node_modules
    - vendor
